文章の修正をしました
AmusementCreators/WebSite pull request #217
Opened 2022-11-28 04:50 UTC by Nagaoka-1

2022-11-28 06:03 UTC, Nagaoka-1 commented
記事の追加しました

2022-11-29 05:30 UTC, kuresugutaira commented
ビルドイメージのサポートが切れていてビルドに失敗していたので先ほどビルドイメージを更新しておきました。
ちょこっと変更を加えると再度ビルドが走ると思うのでそれで確認してみてください。

2022-11-29 08:08 UTC, Nagaoka-1 commented
ファイル名の変更しました

2022-11-29 08:26 UTC, kuresugutaira requested changes
レビューしましたので、修正するか、修正の必要がないと判断した場合は返信くださいませ。

2022-11-29 08:26 UTC, kuresugutaira commented on content/articles/advent_calendar/2022/09.md
> +今回紹介したゲーム以外にも「ito」や「赤ずきんは眠らない」など実家に帰って家族と楽しく遊べるボードゲームはたくさんあります。紅白見ながらでも遊んでみてはいかがでしょうか。
ここにitoって書いてありますが、itoは今回紹介したゲームに含まれているので別のゲームの名前を挙げた方が良さそうです

2022-11-29 08:29 UTC, Nagaoka-1 commented on content/articles/advent_calendar/2022/09.md
> +今回紹介したゲーム以外にも「ito」や「赤ずきんは眠らない」など実家に帰って家族と楽しく遊べるボードゲームはたくさんあります。紅白見ながらでも遊んでみてはいかがでしょうか。
すみません
ありがとうございます

2022-11-29 08:35 UTC, Nagaoka-1 commented
修正しました

2022-11-29 08:53 UTC, kuresugutaira approved these changes

2022-11-29 08:54 UTC, merged